<a href="https://colab.research.google.com/github/kazimayaan/Machine-Learning-Lab/blob/main/backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [14]:
ipn = 2
opn = 2
hln = 4
iteration = 6000

input = np.random.randint(1,5,ipn)
output = np.array([1.0,0.0])
hiddenlayer = np.random.rand(1,hln)

hidden_bias = np.random.rand(1,hln)
output_bias = np.random.rand(1,opn)

hidden_weight = np.random.rand(ipn,hln)
output_weight = np.random.rand(hln,opn)

def sigmoid(layer):
  return 1/(1+np.exp(-layer))

def gradient(layer):
  return layer*(1-layer)

for i in range(iteration):
  hiddenlayer = np.dot(input,hidden_weight)
  hiddenlayer = sigmoid(hiddenlayer+hidden_bias)

  outputlayer = np.dot(hiddenlayer, output_weight)
  outputlayer = sigmoid(outputlayer+output_bias)

  error = output- outputlayer

  gop = gradient(outputlayer)
  error_term_output = gop*error

  error_term_hidden = gradient(hiddenlayer)*np.dot(error_term_output,output_weight.T)

  g_hidden = np.dot(input.reshape(ipn,1), error_term_hidden.reshape(1,hln))
  g_output = np.dot(hiddenlayer.reshape(hln,1), error_term_output.reshape(1,opn))

  hidden_weight = hidden_weight+ 0.5*g_hidden
  output_weight = output_weight + 0.5*g_output

  if i<50 or i>iteration-100:
    print("*********")
    print(error," iteration", i)
    print("#output#",outputlayer)

*********
[[ 0.1855926  -0.84504345]]  iteration 0
#output# [[0.8144074  0.84504345]]
*********
[[ 0.18011949 -0.81829873]]  iteration 1
#output# [[0.81988051 0.81829873]]
*********
[[ 0.17538511 -0.78529032]]  iteration 2
#output# [[0.82461489 0.78529032]]
*********
[[ 0.17126778 -0.74521554]]  iteration 3
#output# [[0.82873222 0.74521554]]
*********
[[ 0.16761843 -0.69802225]]  iteration 4
#output# [[0.83238157 0.69802225]]
*********
[[ 0.16425326 -0.64495261]]  iteration 5
#output# [[0.83574674 0.64495261]]
*********
[[ 0.16097289 -0.58871345]]  iteration 6
#output# [[0.83902711 0.58871345]]
*********
[[ 0.15761082 -0.53285851]]  iteration 7
#output# [[0.84238918 0.53285851]]
*********
[[ 0.15408219 -0.48060668]]  iteration 8
#output# [[0.84591781 0.48060668]]
*********
[[ 0.15039361 -0.43393887]]  iteration 9
#output# [[0.84960639 0.43393887]]
*********
[[ 0.14661099 -0.39348769]]  iteration 10
#output# [[0.85338901 0.39348769]]
*********
[[ 0.14281714 -0.35896546]]  iteration 11
#