<a href="https://colab.research.google.com/github/kazimayaan/Machine-Learning-Lab/blob/main/bap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
ipn = 2
opn = 2
hln = 4
it = 6000

input = np.random.randint(1,5,ipn)
output = np.array([1.0,0.0])
hiddenlayer = np.random.rand(1,hln)

hiddenbias = np.random.rand(1,hln)
outputbias = np.random.rand(1,opn)

hidden_weight = np.random.rand(ipn,hln)
output_weight = np.random.rand(hln,opn)

def sigmoid(layer):
  return 1/(1+ np.exp(-layer))

def gradient(layer):
  return layer*(1-layer)

for i in range(it):
  hiddenlayer = np.dot(input,hidden_weight)
  hiddenlayer = sigmoid(hiddenlayer+hiddenbias)

  outputlayer = np.dot(hiddenlayer,output_weight)
  outputlayer = sigmoid(outputlayer+outputbias)

  error = output-outputlayer

  gop = gradient(outputlayer)
  goh = gradient(hiddenlayer)

  errorop = error*gop
  errorhl = goh * np.dot(errorop,output_weight.T)

  grdh = np.dot(input.reshape(ipn,1),errorhl.reshape(1,hln))
  grdo = np.dot(hiddenlayer.reshape(hln,1),errorop.reshape(1,opn))

  hidden_weight = hidden_weight + 0.5*grdh
  output_weight = output_weight + 0.5*grdo

  if i<50 or i>5500:
    print("--------")
    print(error)
    print(outputlayer)






--------
[[ 0.22793637 -0.96814659]]
[[0.77206363 0.96814659]]
--------
[[ 0.21599075 -0.96649136]]
[[0.78400925 0.96649136]]
--------
[[ 0.20552422 -0.96466476]]
[[0.79447578 0.96466476]]
--------
[[ 0.19628233 -0.96264094]]
[[0.80371767 0.96264094]]
--------
[[ 0.18806443 -0.96038885]]
[[0.81193557 0.96038885]]
--------
[[ 0.18071086 -0.95787093]]
[[0.81928914 0.95787093]]
--------
[[ 0.17409339 -0.95504139]]
[[0.82590661 0.95504139]]
--------
[[ 0.16810807 -0.95184398]]
[[0.83189193 0.95184398]]
--------
[[ 0.16266992 -0.94820904]]
[[0.83733008 0.94820904]]
--------
[[ 0.15770887 -0.94404957]]
[[0.84229113 0.94404957]]
--------
[[ 0.15316668 -0.93925601]]
[[0.84683332 0.93925601]]
--------
[[ 0.14899452 -0.93368915]]
[[0.85100548 0.93368915]]
--------
[[ 0.14515112 -0.92717061]]
[[0.85484888 0.92717061]]
--------
[[ 0.14160117 -0.91947   ]]
[[0.85839883 0.91947   ]]
--------
[[ 0.13831408 -0.91028776]]
[[0.86168592 0.91028776]]
--------
[[ 0.13526274 -0.89923271]]
[[0.86473726 0.899