<a href="https://colab.research.google.com/github/kazimayaan/Machine-Learning-Lab/blob/main/backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
ipn = 2
opn = 2
hln = 4
it = 6000

input = np.random.randint(1,5,ipn)
output = np.array([1.0,0.0])
hiddenlayer = np.random.rand(1,hln)

hiddenbias = np.random.rand(1,hln)
outputbias = np.random.rand(1,opn)

hidden_weight = np.random.rand(ipn,hln)
output_weight = np.random.rand(hln,opn)

def sigmoid(layer):
  return 1/(1+np.exp(-layer))

def gradient(layer):
  return layer*(1-layer)


for i in range (it):
  hiddenlayer = np.dot(input,hidden_weight)
  hiddenlayer = sigmoid(hiddenlayer+hiddenbias)

  outputlayer = np.dot(hiddenlayer,output_weight)
  outputlayer = sigmoid(outputlayer+outputbias)

  error = output-outputlayer

  gop = gradient(outputlayer)
  goh = gradient(hiddenlayer)

  erop = error* gop
  erhl = goh * np.dot(erop,output_weight.T)

  grhl = np.dot(input.reshape(ipn,1),erhl.reshape(1,hln))
  grop = np.dot(hiddenlayer.reshape(hln,1),erop.reshape(1,opn))

  hidden_weight = hidden_weight + 0.5*grhl
  output_weight = output_weight + 0.5*grop

  if i<50 or i>5500:
    print(i)
    print("error::",error)
    print(outputlayer)
    print()

0
error:: [[ 0.12301116 -0.94060548]]
[[0.87698884 0.94060548]]

1
error:: [[ 0.12054598 -0.93485349]]
[[0.87945402 0.93485349]]

2
error:: [[ 0.11823868 -0.92804727]]
[[0.88176132 0.92804727]]

3
error:: [[ 0.11607833 -0.91990918]]
[[0.88392167 0.91990918]]

4
error:: [[ 0.1140557  -0.91006991]]
[[0.8859443  0.91006991]]

5
error:: [[ 0.11216304 -0.89803539]]
[[0.88783696 0.89803539]]

6
error:: [[ 0.11039376 -0.88314422]]
[[0.88960624 0.88314422]]

7
error:: [[ 0.10874191 -0.86451877]]
[[0.89125809 0.86451877]]

8
error:: [[ 0.10720133 -0.84102451]]
[[0.89279867 0.84102451]]

9
error:: [[ 0.10576433 -0.81127919]]
[[0.89423567 0.81127919]]

10
error:: [[ 0.10441939 -0.77380397]]
[[0.89558061 0.77380397]]

11
error:: [[ 0.1031484  -0.72746513]]
[[0.8968516  0.72746513]]

12
error:: [[ 0.10192455 -0.67230783]]
[[0.89807545 0.67230783]]

13
error:: [[ 0.1007142  -0.61050289]]
[[0.8992858  0.61050289]]

14
error:: [[ 0.09948579 -0.54647455]]
[[0.90051421 0.54647455]]

15
error:: [[ 0.0982