<a href="https://colab.research.google.com/github/kazimayaan/Machine-Learning-Lab/blob/main/BPpractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [17]:
ipn = 2
opn = 2
hln = 4
it = 6000

input = np.random.randint(1,5,ipn)
output = np.array([1.0,0.0])
hiddenlayer = np.random.rand(1,hln)

hidden_bias = np.random.rand(1,hln)
output_bias = np.random.rand(1,opn)

hidden_weight = np.random.rand(ipn,hln)
output_weight = np.random.rand(hln,opn)

def sigmoid(layer):
  return 1/(1+np.exp(-layer))

def gradient(layer):
  return layer*(1-layer)

for i in range(it):

  hiddenlayer = np.dot(input, hidden_weight)
  hiddenlayer = sigmoid(hiddenlayer+hidden_bias)

  outputlayer = np.dot(hiddenlayer, output_weight)
  outputlayer = sigmoid(outputlayer+output_bias)

  error = output - outputlayer
  gop = gradient(outputlayer)
  ghl = gradient(hiddenlayer)
  error_term_op = gop*error
  error_term_hl = ghl * np.dot(error_term_op,output_weight.T)
  
  gradient_hidden = np.dot(input.reshape(ipn,1),error_term_hl.reshape(1,hln))
  gradient_output = np.dot(hiddenlayer.reshape(hln,1),error_term_op.reshape(1,opn))

  hidden_weight = hidden_weight + 0.5*gradient_hidden
  output_weight = output_weight + 0.5*gradient_output

  print(error)
  print(outputlayer)
  print()


Streaming output truncated to the last 5000 lines.
[[0.99293091 0.00797325]]

[[ 0.0070684  -0.00797228]]
[[0.9929316  0.00797228]]

[[ 0.0070677  -0.00797132]]
[[0.9929323  0.00797132]]

[[ 0.00706701 -0.00797036]]
[[0.99293299 0.00797036]]

[[ 0.00706632 -0.00796939]]
[[0.99293368 0.00796939]]

[[ 0.00706563 -0.00796843]]
[[0.99293437 0.00796843]]

[[ 0.00706494 -0.00796747]]
[[0.99293506 0.00796747]]

[[ 0.00706425 -0.00796651]]
[[0.99293575 0.00796651]]

[[ 0.00706356 -0.00796555]]
[[0.99293644 0.00796555]]

[[ 0.00706287 -0.00796458]]
[[0.99293713 0.00796458]]

[[ 0.00706218 -0.00796362]]
[[0.99293782 0.00796362]]

[[ 0.00706149 -0.00796266]]
[[0.99293851 0.00796266]]

[[ 0.0070608 -0.0079617]]
[[0.9929392 0.0079617]]

[[ 0.00706011 -0.00796074]]
[[0.99293989 0.00796074]]

[[ 0.00705942 -0.00795978]]
[[0.99294058 0.00795978]]

[[ 0.00705873 -0.00795882]]
[[0.99294127 0.00795882]]

[[ 0.00705804 -0.00795787]]
[[0.99294196 0.00795787]]

[[ 0.00705736 -0.00795691]]
[[0.99294264 0.007